services:
  registry_listener:
    image: ${REGISTRY_HOST}/registry_listener
    build:
      context: ../listener
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=registry_listener
      cache_to:
        - type=gha,scope=registry_listener,mode=max
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    environment:
      DOCKER_HOSTS: unix:///var/run/docker.sock
      OTEL_LOG_LEVEL: debug
      OTEL_TRACES_EXPORTER: console,otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel.next/
